title: خیابان
email: 'omidonrails [at] gmail.com'
description: '! در این وبلاگ دست نوشته های یک انسان خیابانی را میخوانید و احتمالا لذت میبرید'
baseurl: ''
url: ''
twitter_username: omidonrails
github_username: omidonrails
markdown: kramdown
theme: jekyll-theme-mehdix-rtl
plugins:
  - jekyll-feed
